In [8]:
!python -m pip install --upgrade pip


  Using cached pip-25.2-py3-none-any.whl.metadata (4.7 kB)
Using cached pip-25.2-py3-none-any.whl (1.8 MB)
  Attempting uninstall: pip
    Found existing installation: pip 25.1.1
    Uninstalling pip-25.1.1:
      Successfully uninstalled pip-25.1.1


In [9]:
!pip install numpy

import numpy as np
#Creating arrays
arr1=np.array([1, 2, 3, 4, 5]) # 10 array
arr2= np.array([[1, 2, 3], [4, 5, 6]]) #2D array

#Array operations (vectorization)
print(arr1*2) #Multiply each element by 2 
print(arr1+arr1) #Add arrays element-wise

#Reshaping 
arr3 = np.arange(12).reshape(3, 4) #Create 3x4 array from 8-11 print(arr3)

#Matrix operations 
matrix1= np.array([[1,2],[3,4]]) 
matrix2=np.array([[5, 6], [7, 8]])
print(np.dot(matrix1, matrix2))#Matrix multilication

#Statistical operations
data=np.random.normal(0, 1, 1000) #1000 random numbers from normal distribution
print(f"Mean: {data.mean()}, Std: {data.std()}")

[ 2  4  6  8 10]
[ 2  4  6  8 10]
[[19 22]
 [43 50]]
Mean: -0.016967030546427758, Std: 1.0277861244609294


In [12]:
!pip install pandas


   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.0 MB 5.5 MB/s eta 0:00:02
   ------- -------------------------------- 2.1/11.0 MB 6.0 MB/s eta 0:00:02
   -------------- ------------------------- 3.9/11.0 MB 6.8 MB/s eta 0:00:02
   ---------------------- ----------------- 6.3/11.0 MB 8.0 MB/s eta 0:00:01
   ------------------------------- -------- 8.7/11.0 MB 8.8 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 9.3 MB/s  0:00:01

   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   --------------

In [13]:
import pandas as pd
import numpy as np

# Creating DataFrames
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Salary': [50000, 60000, 70000, 80000]
}
df = pd.DataFrame(data)
print(df)

# Reading from CSV (comment corrected)
# df = pd.read_csv('data.csv')  # Make sure the quotes are balanced

# Basic operations
print(df.head(2))             # First 2 rows
print(df.describe())          # Summary statistics
print(df['Age'].mean())       # Average age

# Data selection
print(df[df['Age'] > 30])                         # Filtering
print(df.loc[1:2, ['Name', 'Salary']])            # Selection by label

# Handling missing data
df_with_nan = pd.DataFrame({
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, np.nan, 8]  # Fixed square brackets and values
})
print(df_with_nan.fillna(value=0))                # Replace NaNs with 0
print(df_with_nan.dropna())                       # Drop rows with NaNs

# Grouping
df['Department'] = ['HR', 'Tech', 'Tech', 'HR']
print(df.groupby('Department').mean())            # Average by department

# Merging data
df2 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Eve'],
    'Bonus': [2000, 1500, 3000]  # Fixed brackets
})
print(pd.merge(df, df2, on='Name', how='left'))   # Left join

# Time series functionality
date_rng = pd.date_range(start='1/1/2023', end='1/10/2023', freq='D')
ts = pd.DataFrame(date_rng, columns=['date'])
ts['value'] = np.random.randint(0, 100, size=(len(date_rng)))
ts.set_index('date', inplace=True)                # Fixed method syntax
print(ts.resample('3D').mean())                   # Resample to 3-day periods


      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
3    David   40   80000
    Name  Age  Salary
0  Alice   25   50000
1    Bob   30   60000
             Age        Salary
count   4.000000      4.000000
mean   32.500000  65000.000000
std     6.454972  12909.944487
min    25.000000  50000.000000
25%    28.750000  57500.000000
50%    32.500000  65000.000000
75%    36.250000  72500.000000
max    40.000000  80000.000000
32.5
      Name  Age  Salary
2  Charlie   35   70000
3    David   40   80000
      Name  Salary
1      Bob   60000
2  Charlie   70000
     A    B
0  1.0  5.0
1  2.0  0.0
2  0.0  0.0
3  4.0  8.0
     A    B
0  1.0  5.0
3  4.0  8.0


TypeError: agg function failed [how->mean,dtype->object]

In [14]:
import pandas as pd
import numpy as np

# Creating DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Salary': [50000, 60000, 70000, 80000]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

# Reading from CSV (if needed)
# df = pd.read_csv('data.csv')  # Ensure correct filepath and quotes

# Basic operations
print("\nFirst 2 rows:")
print(df.head(2))

print("\nSummary statistics:")
print(df.describe())

print("\nAverage Age:")
print(df['Age'].mean())

# Data selection
print("\nPeople older than 30:")
print(df[df['Age'] > 30])

print("\nName and Salary of 2nd and 3rd entries:")
print(df.loc[1:2, ['Name', 'Salary']])

# Handling missing data
df_with_nan = pd.DataFrame({
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, np.nan, 8]
})
print("\nMissing values replaced with 0:")
print(df_with_nan.fillna(value=0))

print("\nRows with no missing values:")
print(df_with_nan.dropna())

# Grouping
df['Department'] = ['HR', 'Tech', 'Tech', 'HR']
print("\nAverage Age and Salary by Department:")
print(df.groupby('Department')[['Age', 'Salary']].mean())

# Merging data
df2 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Eve'],
    'Bonus': [2000, 1500, 3000]
})
print("\nMerged DataFrame (Left Join):")
print(pd.merge(df, df2, on='Name', how='left'))

# Time series functionality
date_rng = pd.date_range(start='1/1/2023', end='1/10/2023', freq='D')
ts = pd.DataFrame(date_rng, columns=['date'])
ts['value'] = np.random.randint(0, 100, size=(len(date_rng)))
ts.set_index('date', inplace=True)

print("\nResampled Time Series (3-day average):")
print(ts.resample('3D').mean())


Original DataFrame:
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
3    David   40   80000

First 2 rows:
    Name  Age  Salary
0  Alice   25   50000
1    Bob   30   60000

Summary statistics:
             Age        Salary
count   4.000000      4.000000
mean   32.500000  65000.000000
std     6.454972  12909.944487
min    25.000000  50000.000000
25%    28.750000  57500.000000
50%    32.500000  65000.000000
75%    36.250000  72500.000000
max    40.000000  80000.000000

Average Age:
32.5

People older than 30:
      Name  Age  Salary
2  Charlie   35   70000
3    David   40   80000

Name and Salary of 2nd and 3rd entries:
      Name  Salary
1      Bob   60000
2  Charlie   70000

Missing values replaced with 0:
     A    B
0  1.0  5.0
1  2.0  0.0
2  0.0  0.0
3  4.0  8.0

Rows with no missing values:
     A    B
0  1.0  5.0
3  4.0  8.0

Average Age and Salary by Department:
             Age   Salary
Department               
HR          32.5 